import { StyleSheet } from "react-native";

import { colors } from "./theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    width: "100%",
    maxWidth: 960,
    alignSelf: "center",
    padding: 24,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
  },
  logo: {
    color: colors.foreground,
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  logoAccent: {
    color: colors.green,
  },
  hero: {
    paddingTop: 52,
    paddingBottom: 100,
    position: "relative",
  },
  eyebrow: {
    color: colors.green,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 2,
    marginBottom: 30,
  },
  heroTitle: {
    color: colors.foreground,
    fontSize: 60,
    fontWeight: "900",
    lineHeight: 60,
    letterSpacing: 0.5,
    marginBottom: 28,
  },
  orangeText: {
    color: colors.orange,
  },
  heroDescription: {
    maxWidth: 520,
    color: colors.muted,
    fontSize: 18,
    lineHeight: 29,
    marginBottom: 28,
  },
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  primaryButton: {
    minHeight: 48,
    borderRadius: 24,
    backgroundColor: colors.orange,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: colors.background,
    fontSize: 14,
    fontWeight: "700",
  },
  outlineButton: {
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  outlineButtonText: {
    color: colors.foreground,
    fontSize: 14,
    fontWeight: "600",
  },
  stamp: {
    position: "absolute",
    right: 10,
    top: 48,
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "rgba(169, 204, 89, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-9deg" }],
  },
  stampText: {
    color: colors.foreground,
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 27,
  },
  stampEquals: {
    color: colors.green,
    fontSize: 12,
    fontWeight: "700",
    marginVertical: 2,
  },
  section: {
    paddingVertical: 42,
  },
  sectionLabel: {
    color: colors.green,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 2,
    marginBottom: 32,
  },
  steps: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 28,
  },
  step: {
    flex: 1,
    minWidth: 220,
    gap: 10,
  },
  stepNumber: {
    color: colors.orange,
    fontSize: 14,
    fontWeight: "700",
  },
  stepTitle: {
    color: colors.foreground,
    fontSize: 20,
    fontWeight: "700",
  },
  bodyText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 24,
  },
  goals: {
    marginVertical: 42,
    padding: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(246, 241, 228, 0.1)",
    backgroundColor: "rgba(246, 241, 228, 0.05)",
  },
  goalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 28,
  },
  partnerList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  partnerTag: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  partnerText: {
    color: colors.muted,
    fontSize: 14,
  },
  cta: {
    paddingTop: 58,
    paddingBottom: 70,
    borderTopWidth: 1,
    borderTopColor: "rgba(246, 241, 228, 0.1)",
    gap: 18,
  },
  ctaTitle: {
    maxWidth: 480,
    color: colors.foreground,
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "900",
  },
  form: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    maxWidth: 560,
  },
  input: {
    flex: 1,
    minWidth: 220,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.foreground,
    paddingHorizontal: 20,
    fontSize: 14,
  },
  successText: {
    color: colors.green,
    fontSize: 15,
    fontWeight: "600",
  },
  footer: {
    paddingTop: 28,
    borderTopWidth: 1,
    borderTopColor: "rgba(246, 241, 228, 0.1)",
    color: "rgba(246, 241, 228, 0.5)",
    fontSize: 14,
  },
});
